FROM nginx

LABEL maintainer="Lex Lee <bg5hfc@gmail.com>"

RUN apt-get update \
  && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime 

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 443

CMD ["nginx"]
